package com.tsp_cns_mon.pub_tsp_cns_all_bre_data_rule_publish;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class abc implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public abc() {
    }




}